name: Trigger auto deployment for portfolio-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/portfolio-backend-AutoDeployTrigger-cd227154-bb87-4c05-90d8-52e768b98a5c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PORTFOLIOBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PORTFOLIOBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PORTFOLIOBACKEND_AZURE_SUBSCRIPTION_ID }}
      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.PORTFOLIOBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PORTFOLIOBACKEND_REGISTRY_PASSWORD }}
          containerAppName: portfolio-backend
          resourceGroup: Development
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


